apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgresql.user }}
  DB_PASSWORD: {{ .Values.postgresql.password }}
  POSTGRES_USER: {{ .Values.postgresql.user }}
  POSTGRES_PASS: {{ .Values.postgresql.password }}
