apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgresql.user }}
  DB_PASSWORD: {{ .Values.postgresql.password }}
