apiVersion: v2
name: petclinic
description: Spring PetClinic REST API with PostgreSQL on EKS
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Udaykumar
    email: uday.jsr@gmail.com@example.com
